### ISSUE TITLE
`Cannot find module 'js-yaml'` since 10.18.0

### ISSUE THREAD

**Issue by skirsten** [splitio/javascript-client#662]
After the upgrade from 10.17.3 to 10.18.0 splitio is completely failing to load.

```
Unhandled error
Error: Cannot find module 'js-yaml'
Require stack:
- /app/node_modules/@splitsoftware/splitio-commons/cjs/sync/offline/splitsParser/splitsParserFromFile.js
- /app/node_modules/@splitsoftware/splitio-commons/cjs/sync/offline/LocalhostFromFile.js
- /app/node_modules/@splitsoftware/splitio/lib/settings/node.js
- /app/node_modules/@splitsoftware/splitio/lib/factory/node.js
- /app/node_modules/@splitsoftware/splitio/lib/index.js
- ...
Location
internal/modules/cjs/loader.js:902 - Function.Module._resolveFilename
```

Maybe its related with `js-yaml` version [4.1.0](https://www.npmjs.com/package/js-yaml/v/4.1.0) vs [3.14.1](https://www.npmjs.com/package/js-yaml/v/3.14.1) and CommonJS loading.

**Comment by chillaq** [comment]
Hi @skirsten , I cannot repro using the code below:

const path = require('path');
const SplitFactory = require('@splitsoftware/splitio').SplitFactory;
 var SplitObj = SplitFactory({
    core: {
          authorizationKey: 'localhost'
    },
    features: path.join(__dirname, 'first.yaml'),
    debug: true
});
var client = SplitObj.client();
client.on(client.Event.SDK_READY, () => {
        console.log("SDK is ready");
        console.log(client.getTreatment("id", "first_split"));
        client.destroy();
});

first.yaml file content:
- first_split:
    treatment: 'on'

Could you enable debug logging and repro the issue? Please paste the log and your code here.

**Comment by skirsten** [comment]
I managed to reproduce the problem:

1. Code
```js
require("@splitsoftware/splitio");
```
2. Remove `devDependencies`:
```shell
NODE_ENV=production yarn install
``` 
3. Error
```shell
node test.js
Error: Cannot find module 'js-yaml'
```

So the problem occurs if the distribution only contains the normal "dependencies" and not the "devDependencies".

**Comment by chillaq** [comment]
Thanks @skirsten , checking with the team.

**Comment by EmilianoSanchez** [comment]
Hi @skirsten , 

I am sorry, but I wasn't able to reproduce the issue following your instructions. 
The error `Cannot find module 'js-yaml'` is strange, because `js-yaml` is defined as a `devDependency` in `@splitsoftware/splitio-commons` but as a required `dependency` in `@splitsoftware/splitio`, so it should be present in your project's `node_modules` folder.

Anyway, there is a mismatch of versions between the  [`devDependency`](https://github.com/splitio/javascript-commons/blob/development/package.json#L65) and the [`dependency`](https://github.com/splitio/javascript-client/blob/development/package.json#L40) that might be causing the issue.

There is a release candidate that fixes this dependency mismatch. You can try it with the command `yarn upgrade @splitsoftware/splitio@10.18.1-rc.0` on your project.

Could you also share the versions of yarn and npm that you are using (`yarn --version`, `npm --version`)?
And the outputs of the following commands, to list part of you project dependency tree: `yarn list --pattern js-yaml` and `npm ls js-yaml`.

Regarding your [PR](https://github.com/splitio/javascript-commons/pull/103/files), we would like to avoid defining `js-yaml` as a `dependency` in  splitio-commons because other projects (like the React-Native SDK) also depends on splitio-commons but don't use the modules that requires `js-yaml`.

Thank you,

**Comment by skirsten** [comment]
:+1: I can confirm that `@splitsoftware/splitio@10.18.1-rc.0` fixes the problem.

```shell
$ yarn --version
1.22.15

$ npm --version
8.1.0
```
## `@splitsoftware/splitio@10.18.1-rc.0`

```shell
$ yarn add @splitsoftware/splitio@10.18.1-rc.0
$ NODE_ENV=production yarn install

$ yarn list --pattern js-yaml
yarn list v1.22.15
├─ @istanbuljs/load-nyc-config@1.1.0
│  └─ js-yaml@3.14.1
├─ @splitsoftware/splitio@10.18.1-rc.0
│  └─ js-yaml@3.13.1
└─ js-yaml@4.1.0

$ npm ls js-yaml
***@1.1.11 /home/simon/***
└─┬ @splitsoftware/splitio@10.18.1-rc.0
  ├─┬ @splitsoftware/splitio-commons@1.3.1-rc.0
  │ └── js-yaml@3.13.1 deduped
  └── js-yaml@3.13.1
```

## `@splitsoftware/splitio@10.18.0` (old version)

```shell
$ yarn add @splitsoftware/splitio@10.18.0
$ NODE_ENV=production yarn install

$ yarn list --pattern js-yaml
yarn list v1.22.15
├─ @istanbuljs/load-nyc-config@1.1.0
│  └─ js-yaml@3.14.1
├─ @splitsoftware/splitio@10.18.0
│  └─ js-yaml@3.13.1
└─ js-yaml@4.1.0

$ npm ls js-yaml
***@1.1.11 /home/simon/***
└─┬ @splitsoftware/splitio@10.18.0
  └── js-yaml@3.13.1
```

Seems like eslint and jest were interfering with it on the old version:
```shell
$ yarn why js-yaml
yarn why v1.22.15
[1/4] Why do we have the module "js-yaml"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "js-yaml@4.1.0"
info Has been hoisted to "js-yaml"
info Reasons this module exists
   - Hoisted from "eslint#js-yaml"
   - Hoisted from "eslint#@eslint#eslintrc#js-yaml"
=> Found "@splitsoftware/splitio#js-yaml@3.13.1"
info This module exists because "@splitsoftware#splitio" depends on it.
info Disk size without dependencies: "416KB"
info Disk size with unique dependencies: "956KB"
info Disk size with transitive dependencies: "1.03MB"
info Number of shared dependencies: 2
=> Found "@istanbuljs/load-nyc-config#js-yaml@3.14.1"
info This module exists because "jest#@jest#core#@jest#transform#babel-plugin-istanbul#@istanbuljs#load-nyc-config" depends on it.
```

## New reproduce steps
Also, I created a new empty project and was initially unable to reproduce the problem on the old version (like you noticed). After adding eslint and jest I was able to reproduce the error on the old version and verify the fix on the new version:

```sh
cd `mktemp -d`
yarn init -y
echo 'require("@splitsoftware/splitio");' > index.js

yarn add @splitsoftware/splitio@10.18.0
yarn add -D eslint jest
NODE_ENV=production yarn install
node .
```


> Regarding your [PR](https://github.com/splitio/javascript-commons/pull/103/files), we would like to avoid defining js-yaml as a dependency in splitio-commons because other projects (like the React-Native SDK) also depends on splitio-commons but don't use the modules that requires js-yaml. Instead, other option is to define js-yaml as a peerDependency like https://github.com/splitio/javascript-commons/pull/104.

Makes perfect sense :+1: 

Thank you!

**Comment by EmilianoSanchez** [comment]
Thanks @skirsten  for sharing. 
I was able to reproduce it now, using NPM v8.

Nice to heard it is fixed with the release candidate. 
I will close the issue and let you know when the stable version is released.

**Comment by EmilianoSanchez** [comment]
@skirsten, we have released the version 10.18.1 of the SDK, that includes this update. I am closing this issue, but feel free to reopen it if you find the problem again.

**Comment by julianandrews** [comment]
I just ran into what looks like this same issue using version `10.18.2` and Node `14.18.1`. Upgrading to Node 16 made the issue go away, but I think the fix might not be working for Node 14.

**Comment by mmelograno** [comment]
Hi @gileze33, sorry to hear that.

Could you please share your npm version to try to reproduce it?

Thanks

**Comment by gileze33** [comment]
NPM version 8.1.0
Node version v16.13.0

To repro:
- Basic package json with latest split client
- NODE_ENV=production npm install
- Try requiring the split client

**Comment by EmilianoSanchez** [comment]
Hi @gileze33 , @julianandrews 

Thanks for the reproduction steps. We were finally able to reproduce the issue in NodeJS v14, and decided to move the js-yaml dependency from `@splitsoftware/splitio-commons` to `@splitsoftware/splitio` to avoid this and other resolution issues when using dependencies that also has js-yaml as a production dependency with a different version.

You can try it by upgrading `@splitsoftware/splitio` to version 10.21.0

I am closing the issue for now, but let us know if you find a similar problem again.
